### ISSUE TITLE
is this plugin deprecated?

### ISSUE THREAD

**Issue by jmcampanini** [nebula-plugins/nebula-test#65]
I aske because the [Plugin Overview](http://nebula-plugins.github.io/documentation/plugin_overview.html#deprecated) page shows this plugin to be deprecated. There doesn't seem to be any mention in this repository though...

I really enjoy using this plugin vs the Gradle TestKit mostly because it:

1. removes any boilerplate code required to make the [test code available to the test build](https://docs.gradle.org/current/userguide/test_kit.html#sub:test-kit-classpath-injection)
2. fixes an issue with library ordering in IntelliJ

I see that this project is still:

* receiving updates (updates to the latest version of gradle)
* being used by the other nebula plugins

Is it recommended to use this plugin, at least until the Gradle TestKit gains feature parity?

**Comment by rspieldenner** [comment]
Use is entirely up to you. We'll be moving more and more to TestKit as it gets to speed (we'll be spending some time migrating some of the plugins to the new model and TestKit tests). 2.13 looks to have removed some of the boilerplate on plugin development.

**Comment by bmoylan** [comment]
@jmcampanini I'm currently using this on a 2.13 project for `ProjectSpec`/`PluginProjectSpec` but using TestKit to replace `IntegrationSpec`. `IntegrationSpec` has a lot of useful utilities though, I wonder if it could just be updated to use a TestKit implementation instead of most of `nebula.test.functional.internal`
